##### zeros()
– 괄호 안에 입력된 숫자만큼의 원소를 생성하고
0으로 초기화


In [6]:
import numpy as np

y = np.zeros(shape=(10,), dtype=np.int8)
print(y)
x = np.array([1, 2, 3])
type(x)
x.shape


[0 0 0 0 0 0 0 0 0 0]


(3,)

##### mean()
– 배열에 저장된 원소들의 평균값을 계산

In [10]:
import numpy as np

list_1 = [1, 2, 3]
x = np.array(list_1)
np.mean(x)  #첫번째 방법
x.mean()  #두번째 방법

2.0

#### array()
– Numpy 형식으로 배열의 원소를 입력할 때는 반드시
리스트 형식으로 입력

In [15]:
x = np.array([1, 2, 3]) #리스트
y = np.array((1, 2, 3)) #튜플
z = np.array({1, 2, 3}) #딕셔너리
a = np.array({"a", "b", "c"}) #딕셔너리
print(x,y,z,a)

[1 2 3] [1 2 3] {1, 2, 3} {'a', 'c', 'b'}


#### reshape()
– 배열을 원하는 모양으로 생성

In [23]:
import numpy as np
a = [1,2,3,4,5,6,7,8]
b = np.reshape(a,(2,4))# (2,4) = 2행 4열
c = np.reshape(a,(4,2))
print(b, b.shape, c, c.shape) #shape = 행과 열을 보여준다

[[1 2 3 4]
 [5 6 7 8]] (2, 4) [[1 2]
 [3 4]
 [5 6]
 [7 8]] (4, 2)


#### reshape()
– 3차원 배열 만들기 


In [25]:
a = np.arange(1,9)
print(a)
b = a.reshape(2, 2, 2)
print(b)

[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### reshape를 활용하는 경우를 보다 보면 입력인수로 -1이 들어간 경우가 종종 있다.
reshape()의 ‘-1’이 의미하는 바는, 변경된 배열의 ‘-1’ 위치의 차원은 “원래 배열의 길이와 남은 차원으로 부터 추정”이 된다는 뜻이다.

In [26]:
x = np.arange(12)
x = x.reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
x.reshape(-1, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [28]:
x.reshape(-1, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### ones()
– 배열을 1의 값들로 채움


In [31]:
y = np.ones([3, 4])
print(y)
z = y*2 #ones 응용
print(z)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


#### Numpy 배열의 슬라이싱

In [44]:
list1 = [[1,11],[2,12],[3,13],[4,14]]
np_ary = np.array(list1)
print(np_ary[:, 1])
print(np_ary[:][2])
print(np_ary[3][1])
print(np_ary[1:4])   

[11 12 13 14]
[ 3 13]
14
[[ 2 12]
 [ 3 13]
 [ 4 14]]


#### math 모듈의 sqrt()

In [73]:
import math
math.sqrt(2)
math.sqrt([2]) #math 모듈은 리스트를 인식하지 못한다

TypeError: must be real number, not list

#### Numpy의 sqrt()

In [52]:
import numpy as np 
a = np.sqrt(2)
b = np.sqrt([2, 3, 4]) #numpy는 리스트 값도 인식한다
print(a, b)

1.4142135623730951 [1.41421356 1.73205081 2.        ]


In [64]:
import numpy as np
x = np.zeros(15)
y = np.zeros([5,3])
z = y.reshape([3,5])
z+= 4
print(z)

[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]


#### 전치행렬 transpose()
##### – 행과 열을 교환하여 얻어지는 행렬
– 행렬의 값들을 주대각선을 기준으로 위치를 바꾼 행렬을 의미


In [67]:
import numpy as np
ary = np.array([[1,2],[3,4]])
print(ary.transpose())

[[1 3]
 [2 4]]


In [69]:
import numpy as np
ary = np.array([[1,5],[222,4444]])
print(ary.transpose())

[[   1  222]
 [   5 4444]]


#### 2개 배열에 대한 연산
###### – 2개 배열에 저장된 내용을 인덱스별로 계산
###### – 선형대수학의 사칙연산과 동일하게 작동
###### – 곱셈도 같은 원리로 동작

In [72]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x * y
w = z+1
r = z-1
print(z)
print(w)
print(r)

[ 4 10 18]
[ 5 11 19]
[ 3  9 17]


#### 인덱싱

In [76]:
x = np.array([[1,2,3],[11,22,33],[111,222,333]])
print(x[1])  # x배열의 인덱스 1번의 내용을 출력
print(x[:,1]) # 각 1차원 배열의 1번의 내용을 출력
print(x[1,:]) # x[1,:] = x[1]

[11 22 33]
[  2  22 222]
[11 22 33]


In [83]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(x[0,:]+y[2,:])
print(x[0]+y[2])
print(x[:,1] * y[2,:])


[ 9 11 13]
[ 9 11 13]
[16 45 80]


In [84]:
a = np.array([10,20,30,40,50,60])
b = a >30
print(b)

[False False False  True  True  True]


#### random()

In [91]:
import numpy as np

ary = np.random.random(5)
print(ary)

[0.26420912 0.0910046  0.12617494 0.34166517 0.82024645]


In [95]:
#만들어진 난수 어레이는 주어진 값에 의해 결정되며, [0, 1) 범위에서 균일한 분포를 갖습니다.
a = np.random.rand(5)
print(a)

b = np.random.rand(1, 3, 4)
print(b, b.shape)

[0.52693888 0.2556307  0.01012691 0.5056395  0.58385291]
[[[0.9886864  0.18013258 0.68260861 0.0392867 ]
  [0.81230814 0.98485701 0.13122575 0.20655495]
  [0.37580474 0.9829665  0.7285995  0.49999291]]] (1, 3, 4)


In [117]:
#randint() 범위 지정과 size는 갯수를 뜻한다.
a = np.random.randint(2, size=7)
print(a)

b = np.random.randint(2, 6, size=5)
print(b)

c = np.random.randint(1, 5, size=(2, 3))
print(c)

[1 1 0 1 1 1 1]
[4 2 5 4 2]
[[1 3 4]
 [2 1 4]]


In [123]:
import numpy as np
np.random.seed(0) #seed 는 고정값
print(np.random.rand(2,3))

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]


#### any() 와 all()의 비교

In [139]:
a = np.random.rand(5)
print(a>0.12)
print(np.any(a>0.12))

[ True False  True  True  True]
True


#### linspace()
시작과 끝의 값을 지정하고 그 사이의 값을 균등하게 배분

In [151]:
np.linspace(0, 1112, 5) #(시작값, 끝 값, 분배 수)

array([   0.,  278.,  556.,  834., 1112.])

In [156]:
#retstep=True이면 샘플 간의 간격을 출력
np.linspace(0,100,5, retstep=True)

(array([  0.,  25.,  50.,  75., 100.]), 25.0)

In [157]:
#endpoint=False이면 마지막 값을 제외하고 샘플값을 만들어냄
np.linspace(0,100,5, endpoint=False)

array([ 0., 20., 40., 60., 80.])